### ISSUE TITLE
Intermittent NPE crash with this mod

### ISSUE THREAD

**Issue by Gronglegrowth** [Polarice3/Goety#10]
[Here is the full log](https://mclo.gs/xXg1dLY) as that may offer additional insight into the problem; the crash log is present at the bottom of that.

This has happened to me multiple times before, always whilst loading into a new world for the first time.

**Comment by Polarice3** [comment]
Will fix this in next update!

**Comment by Gronglegrowth** [comment]
This still occurs on the latest released ver of the mod, though given this is still open I guess you knew?
