### ISSUE TITLE
Blocks broken regardless of type or with what do not drop

### ISSUE THREAD

**Issue by Gronglegrowth** [Polarice3/Goety#11]
Whenever a block is broken, an error is printed to the log which seems to point to Goety as the cause. This is with mod version 1.25.0.

> [18:31:56] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
> java.lang.NullPointerException: null
> 	at com.Polarice3.Goety.common.events.ModEvents.SpellLoot(ModEvents.java:1188) ~[goety:1.25.0] {re:classloading}
> 	at net.minecraftforge.eventbus.ASMEventHandler_260_ModEvents_SpellLoot_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
> 	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:388) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:381) ~[forge:?] {re:classloading}
> 	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:99) ~[?:?] {re:classloading,re:mixin}
> 	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading}
> 	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading}
> 	at java.util.function.Predicate.lambda$and$0(Predicate.java:69) ~[?:1.8.0_352] {}
> 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge:?] {re:classloading}
> 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1287) ~[forge:?] {re:classloading}
> 	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
> 	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:636) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:libx.mixins.json:MixinAbstractBlockState,pl:mixin:APP:supplementaries.mixins.json:AbstractBlockMixin,pl:mixin:APP:varodd.mixins.json:AbstractBlockStateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A}
> 	at net.minecraft.block.Block.func_220077_a(Block.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:varodd.mixins.json:BlockMixin,pl:mixin:A}
> 	at net.minecraft.block.Block.func_220054_a(Block.java:258) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:varodd.mixins.json:BlockMixin,pl:mixin:A}
> 	at net.minecraft.block.Block.func_180657_a(Block.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinBlock,pl:mixin:APP:varodd.mixins.json:BlockMixin,pl:mixin:A}
> 	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:257) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.PlayerInteractionManagerMixin,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
> 	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.PlayerInteractionManagerMixin,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
> 	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.artifacts.json:item.diggingclaws.PlayerInteractionManagerMixin,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
> 	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:varodd.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:swem.mixins.json:HorseMovementCheck,pl:mixin:A}
> 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
> 	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
> 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
> 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
> 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
> 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352] {}

**Comment by Gronglegrowth** [comment]
To clarify, as a result of whatever's going on there, blocks don't drop anything at all when mined, including experience.

**Comment by Polarice3** [comment]
What mods/modpack are you using? Are you using a specific item to break blocks?

**Comment by Polarice3** [comment]
Can you try this version and see if the crash still persists?

[https://www.mediafire.com/file/zw8jo2g6cny0hx8/Goety-1.25.1.jar/file](url)

**Comment by Gronglegrowth** [comment]
That one fixed it.

As for your earlier questions, it is a custom modlist with about 60 mods so am unsure how to concisely list them, and I had been testing with empty hand and vanilla diamond pick.

**Comment by Polarice3** [comment]
Excellent! I'll just make sure to see if there are any other problems before I'll upload the new version on Curseforge!

Thank you for your patience!
