### ISSUE TITLE
[2.0.0] Witches robe keybind opens gui even if it is not equipped

### ISSUE THREAD

**Issue by Gronglegrowth** [Polarice3/Goety#13]
Using ver 2.0.0 for 1.19.2, if I press the keybind for the witches robe, it opens its gui even though I do not even have the item in my inventory, let alone equipped.

**Comment by Polarice3** [comment]
Good catch! Will fix it!

**Comment by Polarice3** [comment]
Fixed in Goety 2.0.1!
