### ISSUE TITLE
[Feature Request] Quark compat: Wooden chests and bookshelves.

### ISSUE THREAD

**Issue by wasdspace** [Polarice3/Goety#14]
As the title.
Turning on these two features of Quark will remove the vanilla recipes. It would be very cool if Goety could have its own chests and bookshelves. Seems that Geoty has Haunted, gloom and murk types of wood.
I know that making a mod is very difficult, so this issue is more of a suggestion than a request.
Love your mod!

**Comment by Polarice3** [comment]
Got ya covered! Added in latest version: [1.34.0](https://legacy.curseforge.com/minecraft/mc-mods/goety/files/4555932)

Added it since Quark can make crafting Bookshelves and Chests hard when using Goety's wood!

**Comment by wasdspace** [comment]
Great! Thanks for your work! :)
