### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Qee1y** [Polarice3/Goety#15]
[crash-2023-11-04_20.30.44-server.txt](https://github.com/Polarice3/Goety/files/13258097/crash-2023-11-04_20.30.44-server.txt)
Loading the map will crash

**Comment by Polarice3** [comment]
This repository is for Goety 1, which is in 1.16.5. Submit your issue here for Goety 2: https://github.com/Polarice3/Goety-2/issues

**Comment by Qee1y** [comment]
I'm sorry, I don't know
