### ISSUE TITLE
I can't play on multiplayer server

### ISSUE THREAD

**Issue by C3nt1n3l4x** [Polarice3/Goety#2]
I have a problem when I want to play multiplayer using this mod, I can't connect to the LAN server because I get this message:

internal exception: io.netty.handler.codec.decoderexception: The received encoded string buffer length is lees than zero! Weird string!

It only happens with your mod because if I remove it it works correctly

**Comment by Polarice3** [comment]
Hi! Can you check if the latest update still causes the LAN crash? I'll see what I can do!

**Comment by C3nt1n3l4x** [comment]
Hi! it still causes crash with the latest update, it gives me the same message, the truth is that nobody can connect to my LAN server because of this crash. I hope there's a solution because with the fireNblood mod it worked correctly.
 I'm sorry for my English.

**Comment by Polarice3** [comment]
Hmm... Have you tried opening a new world with the mod? Also, if it's possible, can you paste the crash report here? That would help immensely.

**Comment by C3nt1n3l4x** [comment]
There are no crash log, I only get a message when I want to enter multiplayer.
All updates get the same message but with no error log.

![2022-05-01](https://user-images.githubusercontent.com/105444838/174454575-b05b8489-3806-45ad-9633-9d7625a7178d.png)

**Comment by Polarice3** [comment]
Can you check if the latest update fixes the problem? I'm really sorry you had to go through this, hopefully the update allows you to play online!

**Comment by C3nt1n3l4x** [comment]
Hi, I am sorry to report that it still fails to connect to the server. I made a new world but it doesn't fix the bug. All updates have this bug but there is no crash report.

![2022-05-01](https://user-images.githubusercontent.com/105444838/174593594-350b6c81-6c37-43ca-beba-17cdb9f10b63.png)

**Comment by C3nt1n3l4x** [comment]
hello, now it works correctly on my server. Thank you very much, now I can play online with my friends. Sorry for the inconvenience bro.
