### ISSUE TITLE
Skeleton Minion Crash

### ISSUE THREAD

**Issue by Uraviel** [Polarice3/Goety#5]
While I was testing the mod to install it on my server, I tried summoning different creatures. The zombie, vex, spider, etc works fine but the skeleton crashes the game, including when I spawn it via an egg.
I'm sending you the crash report, hoping it helps you fix the problem. It would bother me not to use your mod on my server, I who am a fan of necromancy, it seemed perfect to me!

> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 02/07/22 18:02
> Description: Ticking player
> 
> java.lang.NoSuchMethodError: net.minecraft.entity.projectile.ProjectileHelper.getWeaponHoldingHand(Lnet/minecraft/entity/LivingEntity;Ljava/util/function/Predicate;)Lnet/minecraft/util/Hand;
> 	at com.Polarice3.Goety.common.entities.ally.SkeletonMinionEntity.reassessWeaponGoal(SkeletonMinionEntity.java:107) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.entities.ally.SkeletonMinionEntity.<init>(SkeletonMinionEntity.java:59) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.spells.SkeletonSpell.WandResult(SkeletonSpell.java:76) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.items.SoulWand.MagicResults(SoulWand.java:449) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.items.SoulWand.func_77654_b(SoulWand.java:193) ~[?:1.15.3] {re:classloading}
> 	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:221) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
> 	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1057) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
> 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer$$Lambda$6238/1478857516.run(Unknown Source) [?:?] {}
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at com.Polarice3.Goety.common.entities.ally.SkeletonMinionEntity.reassessWeaponGoal(SkeletonMinionEntity.java:107) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.entities.ally.SkeletonMinionEntity.<init>(SkeletonMinionEntity.java:59) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.spells.SkeletonSpell.WandResult(SkeletonSpell.java:76) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.items.SoulWand.MagicResults(SoulWand.java:449) ~[?:1.15.3] {re:classloading}
> 	at com.Polarice3.Goety.common.items.SoulWand.func_77654_b(SoulWand.java:193) ~[?:1.15.3] {re:classloading}
> 	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:221) ~[?:?] {re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack}
> 	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1057) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:classloading}
> 	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
> -- Player being ticked --
> Details:
> 	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
> 	Entity ID: 153
> 	Entity Name: Uraviel
> 	Entity's Exact location: 298.22, 73.00, -457.63
> 	Entity's Block location: World: (298,73,-458), Chunk: (at 10,4,6 in 18,-29; contains blocks 288,0,-464 to 303,255,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
> 	Entity's Momentum: 0.00, -0.08, 0.00
> 	Entity's Passengers: []
> 	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
> Stacktrace:
> 	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
> 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.server.MinecraftServer$$Lambda$6238/1478857516.run(Unknown Source) [?:?] {}
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
> 
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1183595944 bytes (1128 MB) / 3019898880 bytes (2880 MB) up to 4294967296 bytes (4096 MB)
> 	CPUs: 16
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	ModLauncher: 8.0.9+86+master.3cf110c
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/mixin-0.8.2.jar mixin PLUGINSERVICE 
> 		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
> 		/forge-1.16.5-36.1.16.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.16.5-36.1.16.jar runtime_enum_extender PLUGINSERVICE 
> 		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.16.5-36.1.16.jar capability_inject_definalize PLUGINSERVICE 
> 		/forge-1.16.5-36.1.16.jar runtimedistcleaner PLUGINSERVICE 
> 		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
> 		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
> 		/forge-1.16.5-36.1.16.jar fml TRANSFORMATIONSERVICE 
> 	FML: 36.1
> 	Forge: net.minecraftforge:36.1.16
> 	FML Language Providers: 
> 		javafml@36.1
> 		minecraft@1
> 	Mod List: 
> 		forge-1.16.5-36.1.16-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
> 		forge-1.16.5-36.1.16-universal.jar                |Forge                         |forge                         |36.1.16             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
> 		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |NOSIGNATURE
> 		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |NOSIGNATURE
> 		Goety-1.15.3.jar                                  |Goety                         |goety                         |1.15.3              |DONE      |NOSIGNATURE
> 		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |DONE      |NOSIGNATURE
> 	Crash Report UUID: c1bdda09-6ab7-4d33-919b-36ea9ccb328a
> 	Patchouli open book context: n/a
> 	Player Count: 1 / 8; [ServerPlayerEntity['Uraviel'/153, l='ServerLevel[Nouveau monde]', x=298.22, y=73.00, z=-457.63]]
> 	Data Packs: vanilla, mod:forge, mod:curios, mod:patchouli (incompatible), mod:goety, mod:jei
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	OptiFine Version: OptiFine_1.16.5_HD_U_G8
> 	OptiFine Build: 20210515-161946
> 	Render Distance Chunks: 17
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.6.0 NVIDIA 512.15
> 	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2
> 	OpenGlVendor: NVIDIA Corporation
> 	CpuCount: 16

**Comment by Polarice3** [comment]
I'll try to fix it for the next update!

**Comment by Uraviel** [comment]
I will be looking forward to it, thanks!
