### ISSUE TITLE
Ticking entity crash.

### ISSUE THREAD

**Issue by wasdspace** [Polarice3/Goety#9]
Goety: 1.23.2
Random crash.
[crash-2022-11-26_20.06.21-server.txt](https://github.com/Polarice3/Goety/files/10096258/crash-2022-11-26_20.06.21-server.txt)
[latest.log](https://github.com/Polarice3/Goety/files/10096260/latest.log)

**Comment by Polarice3** [comment]
I'll see what I can do!

**Comment by Polarice3** [comment]
For anyone encountering this issue, for now go to the mod's Config and disable Urbhadhach Enthrall which is part of the Mob section!
